### PR TITLE
Progress on lexer and added notes.

### PR DESCRIPTION
**Pull request by PrestonKnopp**
This PR contains some progress on the lexer, tests, and notes on Raku.

The notes are some thoughts on how the language could be composed and interface with gdscript.

Let me know what you think.

### CODE REVIEW

**Comment by jebedaia360** [comment]
> All strings are multi-line strings.

Yes and for now for placing tabs and new lines in string Rakugo dev must use `{/tab} {/nl}` - gdscript don't ignore tabs in multi lines strings so I must do it this way, but in raku script we can hide this.
All function statements can be called without parentheses
I like this idea, but it can make code less readable and some devs like to do stuff like this:
```python
some_func(fun2(fun3(fun4()) , some_var) )
```
so our passer will to figure it out from:
```python
some_func fun2 fun3 fun4, some_var
```
It can break it.

> Dictionary field syntax should match GDScript

Yes. 

> Commas are optional in all list contexts.

 So only in lists? why not in dicts also?

> Accessing GDScript

Yes you use it like you described, but unfortunately in gdscript `TYPE_NODE` doesn't exist so for linking nodes to Rakugo there is separeted func :
```python
node_link(node_id: String, node: NodePath)
```
```renpy
define rakugo_var = gd: class Hello: extends Hello
```
We need to catch errors like that before parser.

```python
print "Symbol <[%sym]>" 
```
What `<>` will do?

I see that we need our own print func that will use string parser or we will parse very string?

```python
func define({...rest_named}):
    for key in rest_named:
        gd: Rakugo.define(key, rest_named[key])

func jump(%to_dialog): gd: Rakugo.jump(to_dialog)

jump Minigame jump Scene_id/Node_name/dialog_name

func show(%...parts): gd: if parts.size() > 0: Rakugo.show(parts.join(' '))

show eva smile show bg lecturehall
```
I don't understand we need to recreate Rakugo funcs in Raku?

**Comment by PrestonKnopp** [comment]
> All function statements can be called without parentheses

My thoughts are that only function call statements can be called without parentheses and to remove ambiguity function call expressions are required to have parentheses. The example would look like:

`some_func fun2(fun3(fun4()) , some_var)`

> So only in lists? why not in dicts also?

Oh, I meant things that can be listed like dict fields, function parameters and arguments, etc. I clarified this in the notes.

> unfortunately in gdscript TYPE_NODE doesn't exist so for linking nodes to
> Rakugo there is separeted func

Ah, I'll keep this in mind.

> We need to catch errors like that before parser

I agree. Right now Raku is like an extended subset of GDScript so we'll be able to reuse it to parse some GDScript. In that example we could parse it and see that the gd block contains a class statement in a Raku expression context and report an error.

> What <> will do?

`<>` was just for the print. Removed it.
And the `%` in the print was left by mistake.

> I see that we need our own print func that will use string parser or we will
> parse very string?

I think it would be nice to parse every string and apply string interpolation.

Do you think string interpolation would work with Rakugo's text parser?

> I don't understand we need to recreate Rakugo funcs in Raku?

Here's my reasoning:

1. Separate the implementation from the parser.
    - When new features are added to Rakugo you ideally won't need to touch the
	parser.
2. Provide the parser with static information.
    - We can emit errors for invalid parameter names at parse time.

That's all I got right now.

**Comment by jebedaia360** [comment]
I understand now and agree with all points.
> Do you think string interpolation would work with Rakugo's text parser?

Yes there is all ready option to use string interpolation in Rakugo's text parser by using `[]` in string
For vars declared by `define` func. But there is one problem now.
You see in gdscript version of rakugo I can support diffrent markups, but for Raku I think we can only support one for every thing work correctly, what do you think?
Current rakugo text passer code:   https://github.com/rakugoteam/Rakugo/blob/master/addons/Rakugo/lib/text.gd

**Comment by PrestonKnopp** [comment]
I read through the text passer. That's clever how you delegate the parsing to the RakugoVar class hierarchy.

> For vars declared by define func.

Should there be vars like `var my_var`? Those variables should be interpolative, too.

Another problem: If a variable isn't defined `define my_var` (or declared `var my_var`) in Raku, Raku would not be able to tell if interpolating `[my_var]` is an error or a reference to an externally defined var.

> You see in gdscript version of rakugo I can support diffrent markups, but for Raku I think we can only support one for every thing work correctly, what do you think?

I think that's a good idea to support one markup. What markup is most used by your users?

**Comment by jebedaia360** [comment]
> I read through the text passer. That's clever how you delegate the parsing to the RakugoVar class hierarchy.

Thanks :)

> Should there be vars like var my_var? Those variables should be interpolative, too.

Yes, you see `var my_var` (or maybe `local my_var`) I think will be just normal gdscript var
 and I can and to it in using code like this:
```js
var actual_string = format_string.format({"str": "Godot"})
```
And `define` crates RakugoVar which is always global var.

> Another problem: If a variable isn't defined define my_var (or declared var my_var) in Raku, Raku would not be able to tell if interpolating [my_var] is an error or a reference to an externally defined var.

It can say if this is error - all RakugoVars are added to one big dict at run time.
If it not enough then we can made some script that will try to find define all `define` in other scripts.

> I think that's a good idea to support one markup. What markup is most used by your users?
Form what I see most users uses markup inspired by *Ren'Py*.

**Comment by PrestonKnopp** [comment]
> or maybe `local my_var`

I vote for the `var my_var` form to keep it similar to GDScript.

> format_string.format({"str" : "Godot"})

That sounds like a great idea.

> We can made some script that will try to find define all define in other scripts,
but it still will be not complete - RakugoVars are added when scripts are executed

This is an interesting problem. Let's keep this in mind and for a better solution. Maybe we can just give a warning when we find an unknown variable in an interpolated string?

> Form what I see most users uses markup inspired by Ren'Py.

Okay, cool. I've been reading up on Ren'Py for inspiration. I'll dig deeper into it's syntax.

**Comment by jebedaia360** [comment]
I agree with all points.

**Pull request merged**
